---
abstract: 'Several Tk Add-on widgets (Treeplus, Optionbox, PopUpSelectBox, Statusbox, Checkbox, BootSplash, ProgressBarPlus, CompoundButton (+ legacy-modules: Buttonplus, HListplus, DHList, DTree & HdrResizeButton)'
author:
  - 'M. Krause'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tk-MK
no_index:
  directory:
    - t
    - inc
requires:
  Tk: 804.027
version: 0.23
